### ISSUE TITLE
Study `TpetraCrsColorer_Zoltan2` and `TpetraCrsColorer_Zoltan`

### ISSUE THREAD

**Issue by JacobDomagala** [NexGenAnalytics/Trilinos#10]

**Comment by JacobDomagala** [comment]
Notes:
- TpetraCrsColorer_Zoltan does coloring using culumns 
- By default, Zoltan2 (and Trilinos) uses row coloring (column coloring is not yet implemented)

**Comment by ppebay** [comment]
This issue appears as ready to be closed @egboman

**Comment by egboman** [comment]
Done
