### ISSUE TITLE
Zoltan2:  Convert XpetraCrsMatrixAdapter to Tpetra

### ISSUE THREAD

**Issue by cwschilly** [NexGenAnalytics/Trilinos#44]
Child issue of #26 

- Provide new Zoltan2_TpetraCrsMatrixAdapter that replaces Xpetra one
- Provide meaningful documentation and unit tests for new class

**Comment by cwschilly** [comment]
@stmcgovern This issue can be closed with #26

**Comment by stmcgovern** [comment]
thanks @cwschilly
