### ISSUE TITLE
Integrate Quotient Graph into `miniEM`

### ISSUE THREAD

**Issue by JacobDomagala** [NexGenAnalytics/Trilinos#6]

**Comment by egboman** [comment]
Quotient graph is already an option in MueLu, so only need to change the xml file in miniEM. Note the rebalancing method is specified two or three times (for different subproblems).

**Comment by JacobDomagala** [comment]
Changes needed to switch from MJ to Quotient:
https://github.com/NexGenAnalytics/Trilinos/commit/e21cf850044c37bd23f9ec706cefe1529054ea54

**Comment by JacobDomagala** [comment]
Also we'll probably want to update miniEM to read HIP config file (this will need some changes to source code)

**Comment by JacobDomagala** [comment]
I've created new branch with changes needed:
https://github.com/NexGenAnalytics/Trilinos/tree/zoltan2-test-quotient-with-miniem

**Comment by JacobDomagala** [comment]
OK, we probably will want to enable ParMetis aswell (since QuotientAlg uses ParmetisAlg). The issue is that I don't see parmetis module, hopefully we won't have to build it from source

**Comment by egboman** [comment]
Yes, you will need ParMetis. Sorry forgot about that. I believe it's in a module on Crusher?

**Comment by JacobDomagala** [comment]
I don't see it (running module spider parmetis doesn't show any results). I've seen `module load parmetis/4.0.3` in old build scripts, but this module is no longer present.

**Comment by egboman** [comment]
The OLCF folks promptly installed Parmetis for us:

 module load parmetis/4.0.3

**Comment by JacobDomagala** [comment]
OK, the `parmetis` package is there, but I think we also need `metis`
